
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 20 01:40:07 CET 2014
//----------------------------------------------------

package fr.ensisa.code_generator;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int CLOSE_BRACKET = 11;
  public static final int OPEN_BRACE = 8;
  public static final int CLASS = 6;
  public static final int ID = 3;
  public static final int OPEN_BRACKET = 10;
  public static final int KEYWORD = 7;
  public static final int NUMBER = 2;
  public static final int EOF = 0;
  public static final int CLOSE_BRACE = 9;
  public static final int COMMENT = 4;
  public static final int error = 1;
  public static final int TERM = 5;
}

