
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 21 07:36:29 CET 2014
//----------------------------------------------------

package fr.ensisa.code_generator;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int OPEN_PARENTHESIS = 13;
  public static final int CLOSE_BRACKET = 12;
  public static final int OPEN_BRACE = 9;
  public static final int CLASS = 6;
  public static final int ID = 3;
  public static final int END_CLASS = 15;
  public static final int OPEN_BRACKET = 11;
  public static final int TYPE = 8;
  public static final int KEYWORD = 7;
  public static final int NUMBER = 2;
  public static final int EOF = 0;
  public static final int CLOSE_BRACE = 10;
  public static final int COMMENT = 4;
  public static final int error = 1;
  public static final int CLOSE_PARENTHESIS = 14;
  public static final int TERM = 5;
}

